# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d24801b683b9347a77a1809bbf33a809d0f4e2c32d7b82aa1671eacc56b8c43fafd629baf8e9a10a63d42509cae2eabce1be5785b6a4b494c9aea497b53ef0d

test:
  secret_key_base: 562a32d3677fcb89a4477841714843a37b6edc30d16de280c990519129863b57e53617919a76009f2b757622104b4f3a345bfe3ab9b4f41a7864e1e035dcd6ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
